#!/bin/bash
set -e

echo "Sistema mu: prime operazioni come rete a se stante."
ssh mu sudo sysctl net.ipv4.ip_forward=1
ssh mu sudo sysctl net.ipv4.conf.all.rp_filter=0
ssh mu sudo ip link set dev eth1 address 00:16:3E:2D:8D:DE
ssh mu sudo sysctl net.ipv4.conf.eth1.rp_filter=0
ssh mu sudo sysctl net.ipv4.conf.eth1.arp_ignore=1
ssh mu sudo sysctl net.ipv4.conf.eth1.arp_announce=2
ssh mu sudo ip link set dev eth1 up
ssh mu sudo ip address add 169.254.119.176 dev eth1
ssh mu sudo ip address add 10.0.0.11 dev eth1
ssh mu sudo ip address add 10.0.0.75 dev eth1
ssh mu sudo ip address add 10.0.0.59 dev eth1
ssh mu sudo ip address add 10.0.0.51 dev eth1
ssh mu sudo ip address add 10.0.0.41 dev eth1
(echo; echo "251 ntk # xxx_table_ntk_xxx") | ssh mu sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh mu sudo ip rule add table ntk
ssh mu sudo ip route add unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.24/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.88/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.12/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.76/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.60/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.8/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.72/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.56/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.10/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.74/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.58/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.50/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.40/32 table ntk
ssh mu sudo iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.11
ssh mu sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.12/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.76/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.60/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.8/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.72/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.56/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.10/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.74/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.58/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.50/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.40/32 table ntk
echo "Sistema mu: ingresso del sistema mu nella rete Gdelta."
ssh mu sudo ip route add 169.254.253.216 dev eth1 src 169.254.119.176
echo "Sistema mu: Vecchia identita come connettivita nel nuovo namespace."
ssh mu sudo ip netns add entr01
ssh mu sudo ip link add dev entr01_eth1 link eth1 type macvlan
ssh mu sudo ip link set dev entr01_eth1 netns entr01
ssh mu sudo ip netns exec entr01 ip link set dev entr01_eth1 address 00:16:3E:71:33:12
ssh mu sudo ip netns exec entr01 ip link set dev entr01_eth1 up
ssh mu sudo ip netns exec entr01 ip address add 169.254.101.161 dev entr01_eth1
ssh mu sudo ip netns exec entr01 ip route add 169.254.253.216 dev entr01_eth1 src 169.254.101.161
ssh mu sudo ip netns exec entr01 ip rule add table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.24/29 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.88/29 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.12/30 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.76/30 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.60/30 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.8/31 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.72/31 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.56/31 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.10/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.74/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.58/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.50/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.40/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.11/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.75/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.59/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.51/32 table ntk
ssh mu sudo ip netns exec entr01 ip route add unreachable 10.0.0.41/32 table ntk
ssh mu sudo ip route del 10.0.0.0/29 table ntk
ssh mu sudo ip route del 10.0.0.64/29 table ntk
ssh mu sudo ip route del 10.0.0.16/29 table ntk
ssh mu sudo ip route del 10.0.0.80/29 table ntk
ssh mu sudo ip route del 10.0.0.24/29 table ntk
ssh mu sudo ip route del 10.0.0.88/29 table ntk
ssh mu sudo ip route del 10.0.0.12/30 table ntk
ssh mu sudo ip route del 10.0.0.76/30 table ntk
ssh mu sudo ip route del 10.0.0.60/30 table ntk
ssh mu sudo ip route del 10.0.0.8/31 table ntk
ssh mu sudo ip route del 10.0.0.72/31 table ntk
ssh mu sudo ip route del 10.0.0.56/31 table ntk
ssh mu sudo ip route del 10.0.0.48/31 table ntk
ssh mu sudo ip route del 10.0.0.10/32 table ntk
ssh mu sudo ip route del 10.0.0.74/32 table ntk
ssh mu sudo ip route del 10.0.0.58/32 table ntk
ssh mu sudo ip route del 10.0.0.50/32 table ntk
ssh mu sudo ip route del 10.0.0.40/32 table ntk
ssh mu sudo iptables -t nat -D POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.11
ssh mu sudo ip address del 10.0.0.11/32 dev eth1
ssh mu sudo ip address del 10.0.0.75/32 dev eth1
ssh mu sudo ip address del 10.0.0.59/32 dev eth1
ssh mu sudo ip address del 10.0.0.51/32 dev eth1
ssh mu sudo ip address del 10.0.0.41/32 dev eth1
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.24/29 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.88/29 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.12/30 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.76/30 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.60/30 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.8/31 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.72/31 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.56/31 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.10/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.74/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.58/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.50/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.40/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.11/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.75/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.59/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.51/32 table ntk
ssh mu sudo ip netns exec entr01 ip route change unreachable 10.0.0.41/32 table ntk
echo "Sistema mu: Nuova identita nel namespace default con indirizzo virtuale temporaneo."
ssh mu sudo ip route add unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.8/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.72/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.24/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.88/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.56/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.30/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.94/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.62/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.50/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.28/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.92/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.60/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.48/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.40/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.29/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.93/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.61/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.49/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.41/32 table ntk
echo "Sistema mu: Nuovo arco => nuova tabella."
(echo; echo "250 ntk_from_00:16:3E:1A:C4:45 # xxx_table_ntk_from_00:16:3E:1A:C4:45_xxx") | ssh mu sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh mu sudo ip route add unreachable 10.0.0.0/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.64/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.8/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.72/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.16/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.80/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.24/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.88/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.56/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.30/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.94/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.62/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.50/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.28/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.92/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.60/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.48/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.40/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.29/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.93/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.61/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.49/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.41/32 table ntk_from_00:16:3E:1A:C4:45
echo "Sistema mu: Bootstrap completo. Rotte aggiornate."
ssh mu sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.24/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.88/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.30/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.94/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.62/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.50/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.28/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.92/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.60/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.48/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.40/32 table ntk
ssh mu sudo ip route change 10.0.0.29/32 table ntk via 169.254.253.216 dev eth1
ssh mu sudo ip route change 10.0.0.93/32 table ntk via 169.254.253.216 dev eth1
ssh mu sudo ip route change 10.0.0.61/32 table ntk via 169.254.253.216 dev eth1
ssh mu sudo ip route change 10.0.0.49/32 table ntk via 169.254.253.216 dev eth1
ssh mu sudo ip route change 10.0.0.41/32 table ntk via 169.254.253.216 dev eth1
ssh mu sudo ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.16/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.80/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.24/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.88/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.30/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.94/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.62/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.50/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.28/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.92/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.60/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.48/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.40/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.29/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.93/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.61/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.49/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo iptables -t mangle -A PREROUTING -m mac --mac-source 00:16:3E:1A:C4:45 -j MARK --set-mark 250
ssh mu sudo ip rule add fwmark 250 table ntk_from_00:16:3E:1A:C4:45
echo "Sistema mu: Indirizzo della nuova identita diventa reale."
ssh mu sudo ip address add 10.0.0.28 dev eth1
ssh mu sudo iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.28
ssh mu sudo ip address add 10.0.0.92 dev eth1
ssh mu sudo ip address add 10.0.0.60 dev eth1
ssh mu sudo ip address add 10.0.0.48 dev eth1
ssh mu sudo ip address add 10.0.0.40 dev eth1
ssh mu sudo ip route del 10.0.0.28/32 table ntk
ssh mu sudo ip route del 10.0.0.92/32 table ntk
ssh mu sudo ip route del 10.0.0.60/32 table ntk
ssh mu sudo ip route del 10.0.0.48/32 table ntk
ssh mu sudo ip route del 10.0.0.40/32 table ntk
ssh mu sudo ip route del 10.0.0.28/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.92/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.60/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.48/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.40/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.24/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.88/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.30/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.94/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.62/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.50/31 table ntk
ssh mu sudo ip route change 10.0.0.29/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.28
ssh mu sudo ip route change 10.0.0.93/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.28
ssh mu sudo ip route change 10.0.0.61/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.60
ssh mu sudo ip route change 10.0.0.49/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.48
ssh mu sudo ip route change 10.0.0.41/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.40
ssh mu sudo ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.16/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.80/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.24/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.88/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.30/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.94/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.62/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.50/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.29/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.93/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.61/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.49/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip netns exec entr01 ip route flush table main
ssh mu sudo ip netns exec entr01 ip link delete entr01_eth1 type macvlan
ssh mu sudo ip netns del entr01
echo "Sistema mu: Ingresso come g-nodo (delta+mu) in un'altra rete (beta+gamma=Ggamma)."
ssh mu sudo ip netns add entr03
ssh mu sudo ip link add dev entr03_eth1 link eth1 type macvlan
ssh mu sudo ip link set dev entr03_eth1 netns entr03
ssh mu sudo ip netns exec entr03 ip link set dev entr03_eth1 address 00:16:3E:DF:23:F5
ssh mu sudo ip netns exec entr03 ip link set dev entr03_eth1 up
ssh mu sudo ip netns exec entr03 ip address add 169.254.242.91 dev entr03_eth1
ssh mu sudo ip netns exec entr03 ip route add 169.254.83.167 dev entr03_eth1 src 169.254.242.91
ssh mu sudo ip netns exec entr03 ip rule add table ntk
(echo; echo "249 ntk_from_00:16:3E:B9:77:80 # xxx_table_ntk_from_00:16:3E:B9:77:80_xxx") | ssh mu sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh mu sudo ip netns exec entr03 iptables -t mangle -A PREROUTING -m mac --mac-source 00:16:3E:B9:77:80 -j MARK --set-mark 249
ssh mu sudo ip netns exec entr03 ip rule add fwmark 249 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.41/32 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.41/32 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip route del 10.0.0.29/32 table ntk
ssh mu sudo ip route del 10.0.0.93/32 table ntk
ssh mu sudo ip route del 10.0.0.61/32 table ntk
ssh mu sudo ip route del 10.0.0.49/32 table ntk
ssh mu sudo ip route del 10.0.0.29/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.93/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.61/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.49/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.8/29 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.72/29 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.24/30 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.88/30 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.56/30 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.30/31 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.94/31 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.62/31 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.50/31 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.28/31 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.92/31 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.60/31 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.0/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.64/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.8/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.72/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.16/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.80/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.24/30 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.88/30 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.56/30 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.30/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.94/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.62/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.50/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.28/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.92/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.60/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route add unreachable 10.0.0.48/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip route del 10.0.0.0/29 table ntk
ssh mu sudo ip route del 10.0.0.64/29 table ntk
ssh mu sudo ip route del 10.0.0.8/29 table ntk
ssh mu sudo ip route del 10.0.0.72/29 table ntk
ssh mu sudo ip route del 10.0.0.16/29 table ntk
ssh mu sudo ip route del 10.0.0.80/29 table ntk
ssh mu sudo ip route del 10.0.0.24/30 table ntk
ssh mu sudo ip route del 10.0.0.88/30 table ntk
ssh mu sudo ip route del 10.0.0.56/30 table ntk
ssh mu sudo ip route del 10.0.0.30/31 table ntk
ssh mu sudo ip route del 10.0.0.94/31 table ntk
ssh mu sudo ip route del 10.0.0.62/31 table ntk
ssh mu sudo ip route del 10.0.0.50/31 table ntk
ssh mu sudo ip route del 10.0.0.0/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.64/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.8/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.72/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.16/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.80/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.24/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.88/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.56/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.30/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.94/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.62/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.50/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo iptables -t nat -D POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.28
ssh mu sudo ip address del 10.0.0.28/32 dev eth1
ssh mu sudo ip address del 10.0.0.92/32 dev eth1
ssh mu sudo ip address del 10.0.0.60/32 dev eth1
ssh mu sudo ip address del 10.0.0.48/32 dev eth1
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.8/29 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.72/29 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.24/30 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.88/30 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.56/30 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.30/31 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.94/31 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.62/31 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.50/31 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.28/31 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.92/31 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.60/31 table ntk
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip netns exec entr03 ip route change 10.0.0.41/32 table ntk via 169.254.83.167 dev entr03_eth1
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.16/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.80/29 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.24/30 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.88/30 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.30/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.94/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.62/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.50/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.28/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.92/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.60/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.48/31 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip netns exec entr03 ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:B9:77:80
ssh mu sudo ip route add unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.8/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.72/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.24/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.88/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.16/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.80/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.56/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.20/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.84/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.60/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.22/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.86/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.62/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.50/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.0/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.64/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.8/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.72/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.24/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.88/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.16/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.80/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.56/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.20/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.84/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.60/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.48/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.22/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.86/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.62/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.50/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip address add 10.0.0.20 dev eth1
ssh mu sudo iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.20
ssh mu sudo ip address add 10.0.0.84 dev eth1
ssh mu sudo ip address add 10.0.0.60 dev eth1
ssh mu sudo ip address add 10.0.0.48 dev eth1
ssh mu sudo ip route del 10.0.0.20/31 table ntk
ssh mu sudo ip route del 10.0.0.84/31 table ntk
ssh mu sudo ip route del 10.0.0.60/31 table ntk
ssh mu sudo ip route del 10.0.0.48/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.21/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.85/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.61/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.49/32 table ntk
ssh mu sudo ip route del 10.0.0.20/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.84/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.60/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route del 10.0.0.48/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.21/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.85/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.61/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route add unreachable 10.0.0.49/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.16/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.80/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh mu sudo ip route change 10.0.0.22/31 table ntk via 169.254.253.216 dev eth1 src 10.0.0.20
ssh mu sudo ip route change 10.0.0.86/31 table ntk via 169.254.253.216 dev eth1 src 10.0.0.20
ssh mu sudo ip route change 10.0.0.62/31 table ntk via 169.254.253.216 dev eth1 src 10.0.0.60
ssh mu sudo ip route change 10.0.0.50/31 table ntk via 169.254.253.216 dev eth1 src 10.0.0.48
ssh mu sudo ip route change 10.0.0.21/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.20
ssh mu sudo ip route change 10.0.0.85/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.20
ssh mu sudo ip route change 10.0.0.61/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.60
ssh mu sudo ip route change 10.0.0.49/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.48
ssh mu sudo ip route change 10.0.0.41/32 table ntk via 169.254.253.216 dev eth1 src 10.0.0.40
ssh mu sudo ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.16/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.80/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.22/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.86/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.62/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.50/31 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.21/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.85/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.61/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.49/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:1A:C4:45
ssh mu sudo ip netns exec entr03 ip route flush table main
ssh mu sudo ip netns exec entr03 ip link delete entr03_eth1 type macvlan
ssh mu sudo ip netns del entr03
ssh mu sudo sed -i '/xxx_table_ntk_from_00:16:3E:B9:77:80_xxx/d' /etc/iproute2/rt_tables
echo "TODO Sistema mu: Ingresso di alfa in Ggamma"

