#!/bin/bash
set -e

## Sequenza temporale

### Prime operazioni
echo "Prime operazioni"

echo beta
ssh beta sudo sysctl net.ipv4.ip_forward=1 &>/dev/null
ssh beta sudo sysctl net.ipv4.conf.all.rp_filter=0 &>/dev/null
ssh beta sudo ip link set dev eth1 address 00:16:3E:EC:A3:E1
ssh beta sudo sysctl net.ipv4.conf.eth1.rp_filter=0 &>/dev/null
ssh beta sudo sysctl net.ipv4.conf.eth1.arp_ignore=1 &>/dev/null
ssh beta sudo sysctl net.ipv4.conf.eth1.arp_announce=2 &>/dev/null
ssh beta sudo ip link set dev eth1 up
ssh beta sudo ip address add 169.254.96.141 dev eth1
ssh beta sudo ip address add 10.0.0.10 dev eth1
ssh beta sudo ip address add 10.0.0.74 dev eth1
ssh beta sudo ip address add 10.0.0.58 dev eth1
ssh beta sudo ip address add 10.0.0.50 dev eth1
ssh beta sudo ip address add 10.0.0.40 dev eth1
(echo; echo "251 ntk # xxx_table_ntk_xxx") | ssh beta sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh beta sudo ip rule add table ntk
ssh beta sudo ip route add unreachable 10.0.0.0/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.64/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.16/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.80/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.24/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.88/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.12/30 table ntk
ssh beta sudo ip route add unreachable 10.0.0.76/30 table ntk
ssh beta sudo ip route add unreachable 10.0.0.60/30 table ntk
ssh beta sudo ip route add unreachable 10.0.0.8/31 table ntk
ssh beta sudo ip route add unreachable 10.0.0.72/31 table ntk
ssh beta sudo ip route add unreachable 10.0.0.56/31 table ntk
ssh beta sudo ip route add unreachable 10.0.0.48/31 table ntk
ssh beta sudo ip route add unreachable 10.0.0.11/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.75/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.59/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.51/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.41/32 table ntk
ssh beta sudo iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.10
ssh beta sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.16/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.80/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.12/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.76/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.60/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.8/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.72/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.56/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.48/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.11/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.75/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.59/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.51/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.41/32 table ntk

echo gamma
ssh gamma sudo sysctl net.ipv4.ip_forward=1 &>/dev/null
ssh gamma sudo sysctl net.ipv4.conf.all.rp_filter=0 &>/dev/null
ssh gamma sudo ip link set dev eth1 address 00:16:3E:5B:78:D5
ssh gamma sudo sysctl net.ipv4.conf.eth1.rp_filter=0 &>/dev/null
ssh gamma sudo sysctl net.ipv4.conf.eth1.arp_ignore=1 &>/dev/null
ssh gamma sudo sysctl net.ipv4.conf.eth1.arp_announce=2 &>/dev/null
ssh gamma sudo ip link set dev eth1 up
ssh gamma sudo ip address add 169.254.94.223 dev eth1
ssh gamma sudo ip address add 10.0.0.22 dev eth1
ssh gamma sudo ip address add 10.0.0.86 dev eth1
ssh gamma sudo ip address add 10.0.0.62 dev eth1
ssh gamma sudo ip address add 10.0.0.50 dev eth1
ssh gamma sudo ip address add 10.0.0.40 dev eth1
(echo; echo "251 ntk # xxx_table_ntk_xxx") | ssh gamma sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh gamma sudo ip rule add table ntk
ssh gamma sudo ip route add unreachable 10.0.0.0/29 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.64/29 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.8/29 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.72/29 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.24/29 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.88/29 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.16/30 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.80/30 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.56/30 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.20/31 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.84/31 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.60/31 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.48/31 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.23/32 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.87/32 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.63/32 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.51/32 table ntk
ssh gamma sudo ip route add unreachable 10.0.0.41/32 table ntk
ssh gamma sudo iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.22
ssh gamma sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.16/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.80/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.20/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.84/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.60/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.48/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.23/32 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.87/32 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.63/32 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.51/32 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.41/32 table ntk

echo delta
ssh delta sudo sysctl net.ipv4.ip_forward=1 &>/dev/null
ssh delta sudo sysctl net.ipv4.conf.all.rp_filter=0 &>/dev/null
ssh delta sudo ip link set dev eth1 address 00:16:3E:1A:C4:45
ssh delta sudo sysctl net.ipv4.conf.eth1.rp_filter=0 &>/dev/null
ssh delta sudo sysctl net.ipv4.conf.eth1.arp_ignore=1 &>/dev/null
ssh delta sudo sysctl net.ipv4.conf.eth1.arp_announce=2 &>/dev/null
ssh delta sudo ip link set dev eth1 up
ssh delta sudo ip address add 169.254.253.216 dev eth1
ssh delta sudo ip address add 10.0.0.29 dev eth1
ssh delta sudo ip address add 10.0.0.93 dev eth1
ssh delta sudo ip address add 10.0.0.61 dev eth1
ssh delta sudo ip address add 10.0.0.49 dev eth1
ssh delta sudo ip address add 10.0.0.41 dev eth1
(echo; echo "251 ntk # xxx_table_ntk_xxx") | ssh delta sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh delta sudo ip rule add table ntk
ssh delta sudo ip route add unreachable 10.0.0.0/29 table ntk
ssh delta sudo ip route add unreachable 10.0.0.64/29 table ntk
ssh delta sudo ip route add unreachable 10.0.0.8/29 table ntk
ssh delta sudo ip route add unreachable 10.0.0.72/29 table ntk
ssh delta sudo ip route add unreachable 10.0.0.16/29 table ntk
ssh delta sudo ip route add unreachable 10.0.0.80/29 table ntk
ssh delta sudo ip route add unreachable 10.0.0.24/30 table ntk
ssh delta sudo ip route add unreachable 10.0.0.88/30 table ntk
ssh delta sudo ip route add unreachable 10.0.0.56/30 table ntk
ssh delta sudo ip route add unreachable 10.0.0.30/31 table ntk
ssh delta sudo ip route add unreachable 10.0.0.94/31 table ntk
ssh delta sudo ip route add unreachable 10.0.0.62/31 table ntk
ssh delta sudo ip route add unreachable 10.0.0.50/31 table ntk
ssh delta sudo ip route add unreachable 10.0.0.28/32 table ntk
ssh delta sudo ip route add unreachable 10.0.0.92/32 table ntk
ssh delta sudo ip route add unreachable 10.0.0.60/32 table ntk
ssh delta sudo ip route add unreachable 10.0.0.48/32 table ntk
ssh delta sudo ip route add unreachable 10.0.0.40/32 table ntk
ssh delta sudo iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.29
ssh delta sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh delta sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh delta sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh delta sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh delta sudo ip route change unreachable 10.0.0.16/29 table ntk
ssh delta sudo ip route change unreachable 10.0.0.80/29 table ntk
ssh delta sudo ip route change unreachable 10.0.0.24/30 table ntk
ssh delta sudo ip route change unreachable 10.0.0.88/30 table ntk
ssh delta sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh delta sudo ip route change unreachable 10.0.0.30/31 table ntk
ssh delta sudo ip route change unreachable 10.0.0.94/31 table ntk
ssh delta sudo ip route change unreachable 10.0.0.62/31 table ntk
ssh delta sudo ip route change unreachable 10.0.0.50/31 table ntk
ssh delta sudo ip route change unreachable 10.0.0.28/32 table ntk
ssh delta sudo ip route change unreachable 10.0.0.92/32 table ntk
ssh delta sudo ip route change unreachable 10.0.0.60/32 table ntk
ssh delta sudo ip route change unreachable 10.0.0.48/32 table ntk
ssh delta sudo ip route change unreachable 10.0.0.40/32 table ntk

echo mu
ssh mu sudo sysctl net.ipv4.ip_forward=1 &>/dev/null
ssh mu sudo sysctl net.ipv4.conf.all.rp_filter=0 &>/dev/null
ssh mu sudo ip link set dev eth1 address 00:16:3E:2D:8D:DE
ssh mu sudo sysctl net.ipv4.conf.eth1.rp_filter=0 &>/dev/null
ssh mu sudo sysctl net.ipv4.conf.eth1.arp_ignore=1 &>/dev/null
ssh mu sudo sysctl net.ipv4.conf.eth1.arp_announce=2 &>/dev/null
ssh mu sudo ip link set dev eth1 up
ssh mu sudo ip address add 169.254.119.176 dev eth1
ssh mu sudo ip address add 10.0.0.11 dev eth1
ssh mu sudo ip address add 10.0.0.75 dev eth1
ssh mu sudo ip address add 10.0.0.59 dev eth1
ssh mu sudo ip address add 10.0.0.51 dev eth1
ssh mu sudo ip address add 10.0.0.41 dev eth1
(echo; echo "251 ntk # xxx_table_ntk_xxx") | ssh mu sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh mu sudo ip rule add table ntk
ssh mu sudo ip route add unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.24/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.88/29 table ntk
ssh mu sudo ip route add unreachable 10.0.0.12/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.76/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.60/30 table ntk
ssh mu sudo ip route add unreachable 10.0.0.8/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.72/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.56/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip route add unreachable 10.0.0.10/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.74/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.58/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.50/32 table ntk
ssh mu sudo ip route add unreachable 10.0.0.40/32 table ntk
ssh mu sudo iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.11
ssh mu sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.16/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.80/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh mu sudo ip route change unreachable 10.0.0.12/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.76/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.60/30 table ntk
ssh mu sudo ip route change unreachable 10.0.0.8/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.72/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.56/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.48/31 table ntk
ssh mu sudo ip route change unreachable 10.0.0.10/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.74/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.58/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.50/32 table ntk
ssh mu sudo ip route change unreachable 10.0.0.40/32 table ntk

### Ingresso di 𝛽 in G𝛾
echo "Ingresso beta in G-gamma"

ssh beta sudo ip route add 169.254.94.223 dev eth1 src 169.254.96.141

ssh gamma sudo ip route add 169.254.96.141 dev eth1 src 169.254.94.223

ssh beta sudo ip netns add entr02
ssh beta sudo ip netns exec entr02 sysctl net.ipv4.ip_forward=1 &>/dev/null
ssh beta sudo ip netns exec entr02 sysctl net.ipv4.conf.all.rp_filter=0 &>/dev/null
ssh beta sudo ip link add dev entr02_eth1 link eth1 type macvlan
ssh beta sudo ip link set dev entr02_eth1 netns entr02
ssh beta sudo ip netns exec entr02 ip link set dev entr02_eth1 address 00:16:3E:8E:91:B9
ssh beta sudo ip netns exec entr02 sysctl net.ipv4.conf.entr02_eth1.rp_filter=0 &>/dev/null
ssh beta sudo ip netns exec entr02 sysctl net.ipv4.conf.entr02_eth1.arp_ignore=1 &>/dev/null
ssh beta sudo ip netns exec entr02 sysctl net.ipv4.conf.entr02_eth1.arp_announce=2 &>/dev/null
ssh beta sudo ip netns exec entr02 ip link set dev entr02_eth1 up
ssh beta sudo ip netns exec entr02 ip address add 169.254.215.29 dev entr02_eth1
ssh beta sudo ip netns exec entr02 ip route add 169.254.94.223 dev entr02_eth1 src 169.254.215.29

ssh gamma sudo ip route add 169.254.215.29 dev eth1 src 169.254.94.223

echo "beta0 in networkspace entr02"
ssh beta sudo ip netns exec entr02 ip rule add table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.0/29 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.64/29 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.16/29 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.80/29 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.24/29 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.88/29 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.12/30 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.76/30 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.60/30 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.8/31 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.72/31 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.56/31 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.48/31 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.11/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.75/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.59/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.51/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.41/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.10/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.74/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.58/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.50/32 table ntk
ssh beta sudo ip netns exec entr02 ip route add unreachable 10.0.0.40/32 table ntk
ssh beta sudo ip route del 10.0.0.0/29 table ntk
ssh beta sudo ip route del 10.0.0.64/29 table ntk
ssh beta sudo ip route del 10.0.0.16/29 table ntk
ssh beta sudo ip route del 10.0.0.80/29 table ntk
ssh beta sudo ip route del 10.0.0.24/29 table ntk
ssh beta sudo ip route del 10.0.0.88/29 table ntk
ssh beta sudo ip route del 10.0.0.12/30 table ntk
ssh beta sudo ip route del 10.0.0.76/30 table ntk
ssh beta sudo ip route del 10.0.0.60/30 table ntk
ssh beta sudo ip route del 10.0.0.8/31 table ntk
ssh beta sudo ip route del 10.0.0.72/31 table ntk
ssh beta sudo ip route del 10.0.0.56/31 table ntk
ssh beta sudo ip route del 10.0.0.48/31 table ntk
ssh beta sudo ip route del 10.0.0.11/32 table ntk
ssh beta sudo ip route del 10.0.0.75/32 table ntk
ssh beta sudo ip route del 10.0.0.59/32 table ntk
ssh beta sudo ip route del 10.0.0.51/32 table ntk
ssh beta sudo ip route del 10.0.0.41/32 table ntk
ssh beta sudo iptables -t nat -D POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.10
ssh beta sudo ip address del 10.0.0.10/32 dev eth1
ssh beta sudo ip address del 10.0.0.74/32 dev eth1
ssh beta sudo ip address del 10.0.0.58/32 dev eth1
ssh beta sudo ip address del 10.0.0.50/32 dev eth1
ssh beta sudo ip address del 10.0.0.40/32 dev eth1
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.0/29 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.64/29 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.16/29 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.80/29 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.24/29 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.88/29 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.12/30 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.76/30 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.60/30 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.8/31 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.72/31 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.56/31 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.48/31 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.11/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.75/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.59/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.51/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.41/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.10/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.74/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.58/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.50/32 table ntk
ssh beta sudo ip netns exec entr02 ip route change unreachable 10.0.0.40/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.0/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.64/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.8/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.72/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.24/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.88/29 table ntk
ssh beta sudo ip route add unreachable 10.0.0.16/30 table ntk
ssh beta sudo ip route add unreachable 10.0.0.80/30 table ntk
ssh beta sudo ip route add unreachable 10.0.0.56/30 table ntk
ssh beta sudo ip route add unreachable 10.0.0.20/31 table ntk
ssh beta sudo ip route add unreachable 10.0.0.84/31 table ntk
ssh beta sudo ip route add unreachable 10.0.0.60/31 table ntk
ssh beta sudo ip route add unreachable 10.0.0.48/31 table ntk
ssh beta sudo ip route add unreachable 10.0.0.22/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.86/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.62/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.50/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.40/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.23/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.87/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.63/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.51/32 table ntk
ssh beta sudo ip route add unreachable 10.0.0.41/32 table ntk

echo "beta1 in G-gamma"
(echo; echo "250 ntk_from_00:16:3E:5B:78:D5 # xxx_table_ntk_from_00:16:3E:5B:78:D5_xxx") | ssh beta sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh beta sudo ip route add unreachable 10.0.0.0/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.64/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.8/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.72/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.24/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.88/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.16/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.80/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.56/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.20/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.84/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.60/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.48/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.22/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.86/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.62/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.50/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.40/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.23/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.87/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.63/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.51/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route add unreachable 10.0.0.41/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.16/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.80/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.20/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.84/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.60/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.48/31 table ntk
ssh beta sudo ip route change 10.0.0.22/32 table ntk via 169.254.94.223 dev eth1
ssh beta sudo ip route change 10.0.0.86/32 table ntk via 169.254.94.223 dev eth1
ssh beta sudo ip route change 10.0.0.62/32 table ntk via 169.254.94.223 dev eth1
ssh beta sudo ip route change 10.0.0.50/32 table ntk via 169.254.94.223 dev eth1
ssh beta sudo ip route change 10.0.0.40/32 table ntk via 169.254.94.223 dev eth1
ssh beta sudo ip route change unreachable 10.0.0.23/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.87/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.63/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.51/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.41/32 table ntk
ssh beta sudo ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.16/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.80/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.20/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.84/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.60/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.48/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.22/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.86/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.62/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.50/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.40/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.23/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.87/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.63/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.51/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo iptables -t mangle -A PREROUTING -m mac --mac-source 00:16:3E:5B:78:D5 -j MARK --set-mark 250
ssh beta sudo ip rule add fwmark 250 table ntk_from_00:16:3E:5B:78:D5

(echo; echo "250 ntk_from_00:16:3E:EC:A3:E1 # xxx_table_ntk_from_00:16:3E:EC:A3:E1_xxx") | ssh gamma sudo tee -a /etc/iproute2/rt_tables >/dev/null
ssh gamma sudo ip route add unreachable 10.0.0.0/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.64/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.8/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.72/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.24/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.88/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.16/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.80/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.56/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.20/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.84/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.60/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.48/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.23/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.87/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.63/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.51/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route add unreachable 10.0.0.41/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.16/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.80/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.20/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.84/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.60/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.48/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.23/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.87/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.63/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.51/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.16/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.80/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.20/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.84/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.60/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.48/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.23/32 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.87/32 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.63/32 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.51/32 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.41/32 table ntk
ssh gamma sudo iptables -t mangle -A PREROUTING -m mac --mac-source 00:16:3E:EC:A3:E1 -j MARK --set-mark 250
ssh gamma sudo ip rule add fwmark 250 table ntk_from_00:16:3E:EC:A3:E1

ssh beta sudo ip address add 10.0.0.23 dev eth1
ssh beta sudo iptables -t nat -A POSTROUTING -d 10.0.0.64/27 -j SNAT --to 10.0.0.23
ssh beta sudo ip address add 10.0.0.87 dev eth1
ssh beta sudo ip address add 10.0.0.63 dev eth1
ssh beta sudo ip address add 10.0.0.51 dev eth1
ssh beta sudo ip address add 10.0.0.41 dev eth1
ssh beta sudo ip route del 10.0.0.23/32 table ntk
ssh beta sudo ip route del 10.0.0.87/32 table ntk
ssh beta sudo ip route del 10.0.0.63/32 table ntk
ssh beta sudo ip route del 10.0.0.51/32 table ntk
ssh beta sudo ip route del 10.0.0.41/32 table ntk
ssh beta sudo ip route del 10.0.0.23/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route del 10.0.0.87/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route del 10.0.0.63/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route del 10.0.0.51/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route del 10.0.0.41/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh beta sudo ip route change unreachable 10.0.0.16/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.80/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh beta sudo ip route change unreachable 10.0.0.20/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.84/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.60/31 table ntk
ssh beta sudo ip route change unreachable 10.0.0.48/31 table ntk
ssh beta sudo ip route change 10.0.0.22/32 table ntk via 169.254.94.223 dev eth1 src 10.0.0.23
ssh beta sudo ip route change 10.0.0.86/32 table ntk via 169.254.94.223 dev eth1 src 10.0.0.23
ssh beta sudo ip route change 10.0.0.62/32 table ntk via 169.254.94.223 dev eth1 src 10.0.0.63
ssh beta sudo ip route change 10.0.0.50/32 table ntk via 169.254.94.223 dev eth1 src 10.0.0.51
ssh beta sudo ip route change 10.0.0.40/32 table ntk via 169.254.94.223 dev eth1 src 10.0.0.41
ssh beta sudo ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.16/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.80/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.20/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.84/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.60/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.48/31 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.22/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.86/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.62/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.50/32 table ntk_from_00:16:3E:5B:78:D5
ssh beta sudo ip route change unreachable 10.0.0.40/32 table ntk_from_00:16:3E:5B:78:D5

ssh gamma sudo ip route change unreachable 10.0.0.0/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.64/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.8/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.72/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.24/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.88/29 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.16/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.80/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.56/30 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.20/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.84/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.60/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.48/31 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.23/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.87/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.63/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.51/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.41/32 table ntk_from_00:16:3E:EC:A3:E1
ssh gamma sudo ip route change unreachable 10.0.0.0/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.64/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.8/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.72/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.24/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.88/29 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.16/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.80/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.56/30 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.20/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.84/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.60/31 table ntk
ssh gamma sudo ip route change unreachable 10.0.0.48/31 table ntk
ssh gamma sudo ip route change 10.0.0.23/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.22
ssh gamma sudo ip route change 10.0.0.87/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.22
ssh gamma sudo ip route change 10.0.0.63/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.62
ssh gamma sudo ip route change 10.0.0.51/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.50
ssh gamma sudo ip route change 10.0.0.41/32 table ntk via 169.254.96.141 dev eth1 src 10.0.0.40

echo "beta0 dismessa"
ssh beta sudo ip netns exec entr02 ip route flush table main
ssh beta sudo ip netns exec entr02 ip link delete entr02_eth1 type macvlan
ssh beta sudo ip netns del entr02

ssh gamma sudo ip route del 169.254.215.29 dev eth1 src 169.254.94.223

echo "beta vede gamma e viceversa"
ssh beta "ping -q -n -c 1 10.0.0.22 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.22"; exit 1)
ssh beta "ping -q -n -c 1 10.0.0.86 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.86"; exit 1)
ssh beta "ping -q -n -c 1 10.0.0.62 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.62"; exit 1)
ssh beta "ping -q -n -c 1 10.0.0.50 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.50"; exit 1)
ssh beta "ping -q -n -c 1 10.0.0.40 -W 1 &>/dev/null" || (echo "beta: errore ping 10.0.0.40"; exit 1)

echo "test completato"

